# Generated by Django 3.1 on 2020-09-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='generalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sprinkler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=25)),
                ('power', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='waterQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('waterQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeStart', models.DateTimeField()),
                ('timeEnd', models.DateTimeField()),
                ('sprinklerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinklercontrolapp.sprinkler')),
            ],
        ),
        migrations.CreateModel(
            name='sprinklerError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('timeStart', models.DateTimeField()),
                ('timeEnd', models.DateTimeField()),
                ('errorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinklercontrolapp.error')),
                ('sprinklerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinklercontrolapp.sprinkler')),
            ],
        ),
        migrations.CreateModel(
            name='restrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('timeStart', models.DateTimeField()),
                ('timeEnd', models.DateTimeField()),
                ('description', models.CharField(max_length=25)),
                ('sprinklerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinklercontrolapp.sprinkler')),
            ],
        ),
    ]
