# Generated by Django 3.1.1 on 2020-09-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprinkler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, verbose_name='Bezeichnung')),
                ('description', models.CharField(max_length=150, verbose_name='Ort/Beschreibung')),
                ('power', models.BooleanField(verbose_name='Eingeschaltet')),
                ('enabled', models.BooleanField(verbose_name='Aktiviert')),
            ],
            options={
                'verbose_name_plural': 'Sprinklers',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='Bezeichnung')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRepeatingTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, verbose_name='Bezeichnung')),
                ('description', models.CharField(max_length=150, verbose_name='Beschreibung')),
                ('timestart', models.TimeField(verbose_name='Startzeit')),
                ('timestop', models.TimeField(verbose_name='Stopzeit')),
                ('sprinklers', models.ManyToManyField(to='sprinklercontrolapp.Sprinkler')),
                ('weekdays', models.ManyToManyField(to='sprinklercontrolapp.Weekday')),
            ],
        ),
    ]
