# Generated by Django 3.1 on 2020-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklercontrolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprinkler',
            options={'verbose_name_plural': 'Sprinklers'},
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='label',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
