# Generated by Django 3.1.1 on 2020-09-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklercontrolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrepeatingtimer',
            name='weekdays',
            field=models.ManyToManyField(to='sprinklercontrolapp.Weekday'),
        ),
    ]
