# Generated by Django 3.1 on 2020-09-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklercontrolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='irrigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('timeStart', models.DateTimeField()),
                ('timeEnd', models.DateTimeField()),
                ('sprinklerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprinklercontrolapp.sprinkler')),
            ],
        ),
    ]
