# Generated by Django 3.1 on 2020-09-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklercontrolapp', '0002_auto_20200908_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinkler',
            name='enabled',
            field=models.BooleanField(verbose_name='Aktiviert'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='label',
            field=models.CharField(max_length=40, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Ort/Beschreibung'),
        ),
        migrations.AlterField(
            model_name='sprinkler',
            name='power',
            field=models.BooleanField(verbose_name='Eingeschaltet'),
        ),
    ]
