# Generated by Django 3.1 on 2020-09-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklercontrolapp', '0003_auto_20200909_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRepeatingTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, verbose_name='Bezeichnung')),
                ('description', models.CharField(max_length=150, verbose_name='Bezeichnung')),
                ('timestart', models.TimeField(verbose_name='Startzeit')),
                ('timestop', models.TimeField(verbose_name='Stopzeit')),
                ('monday', models.BooleanField(verbose_name='Montag')),
                ('tuesday', models.BooleanField(verbose_name='Dienstag')),
                ('wednesday', models.BooleanField(verbose_name='Mittwoch')),
                ('thursday', models.BooleanField(verbose_name='Donnerstag')),
                ('friday', models.BooleanField(verbose_name='Freitag')),
                ('saturday', models.BooleanField(verbose_name='Samstag')),
                ('sunday', models.BooleanField(verbose_name='Sonntag')),
            ],
        ),
    ]
